<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="System_IpcInfo" Id="{6baa2aa1-d5d7-4b2b-87dd-5d6201c5627a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK System_IpcInfo
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="System_IpcInfo">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>