<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Day" Id="{1b30805a-7895-4c0e-82ff-d0c87ad5a04b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Day
VAR_INPUT
	
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Day">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>