<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PtHelper" Id="{93a8a7c4-f8ae-48de-beae-d3ef81074e3d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PtHelper
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PtHelper">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>