<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="System_IpcInfo" Id="{1eda1d9f-cba2-4733-9d4e-4996c44e80f7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK System_IpcInfo
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="System_IpcInfo">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>