<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="isLeapYear" Id="{6342e5f8-04b6-4083-87c4-cf21a7f0562e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION isLeapYear : BOOL
VAR_INPUT
	Year : DINT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[isLeapYear := (year mod 4 = 0) and ((year mod 100 <> 0) or (year mod 400 = 0));]]></ST>
    </Implementation>
    <LineIds Name="isLeapYear">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>