<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_TimeStamp13_TO_SYSTEMTIME_1" Id="{71076591-af9d-470f-97c9-f2551f56bbd2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_TimeStamp13_TO_SYSTEMTIME_1 : TimeStruct
VAR_INPUT
	iUnixTimeStamp13 : ULINT;
END_VAR
VAR
	_FileTime64 :T_FILETIME64;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[_FileTime64 := (iUnixTimeStamp13 + 11644473600000 - 5000) * 10000;
F_TimeStamp13_TO_SYSTEMTIME := FILETIME64_TO_SYSTEMTIME(_FileTime64);]]></ST>
    </Implementation>
    <LineIds Name="F_TimeStamp13_TO_SYSTEMTIME_1">
      <LineId Id="7" Count="0" />
      <LineId Id="24" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>